In [1]:
%pylab
%matplotlib inline
%config InlineBackend.figure_format = 'svg'


Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [59]:
from sklearn import linear_model,preprocessing
from matplotlib import pyplot as plt
import csv
import numpy as np

In [96]:
with open('train_titanic.csv', 'r') as fr:
    freader = csv.reader(fr)
    cnt = 0
    labels = []
    features = []
    for eachLine in freader:
        cnt += 1
        if (cnt > 1):
            feature = np.zeros(shape=(11, ))
            feature[int(eachLine[2])-1] = 1
            feature[3] = int(eachLine[4] == 'male')
            try:
                feature[4] = float(eachLine[5])
            except:
                feature[4] = 30
            feature[5] = int(eachLine[6])
            feature[6] = int(eachLine[7])
            feature[7] = float(eachLine[9])
            offset = 0
            if (eachLine[11] == 'S'):
                offset = 0
            elif (eachLine[11] == 'C'):
                offset = 1
            else:
                offset = 2
            feature[8+offset] = 1
            features.append(feature)
            labels.append(int(eachLine[1]))

    features = np.array(features, dtype = float)
    labels = np.array(labels, dtype = int).reshape(-1, )
    print(features.shape)
            
        

(891, 11)


In [98]:
to_scale = features[:,[4,5,6,7]]
print(to_scale)
to_scale = preprocessing.scale(to_scale)
print(to_scale)
features[:,[4,5,6,7]] = to_scale
print(features)

[[-0.59705478  0.43279337 -0.47367361 -0.50244517]
 [ 0.63416229  0.43279337 -0.47367361  0.78684529]
 [-0.28925051 -0.4745452  -0.47367361 -0.48885426]
 ...
 [ 0.01855376  0.43279337  2.00893337 -0.17626324]
 [-0.28925051 -0.4745452  -0.47367361 -0.04438104]
 [ 0.17245589 -0.4745452  -0.47367361 -0.49237783]]
[[-0.59705478  0.43279337 -0.47367361 -0.50244517]
 [ 0.63416229  0.43279337 -0.47367361  0.78684529]
 [-0.28925051 -0.4745452  -0.47367361 -0.48885426]
 ...
 [ 0.01855376  0.43279337  2.00893337 -0.17626324]
 [-0.28925051 -0.4745452  -0.47367361 -0.04438104]
 [ 0.17245589 -0.4745452  -0.47367361 -0.49237783]]
[[0. 0. 1. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]]


In [33]:
ind = np.random.choice(891, 446, replace=False)

train_half_X = features[ind]
train_half_Y = labels[ind]


ind_ = []
mask = [0 for i in range(891)]
print(len(mask))
for i in ind:
    mask[i] = 1
for i in range(891):
    if (mask[i] == 0):
        ind_.append(i)
val_half_X = features[ind_]
val_half_Y = labels[ind_]
        
lr.fit(train_half_X, train_half_Y)

NameError: name 'features' is not defined

In [102]:
preds = lr.predict(val_half_X)
print(preds.shape)


print('accuracy on valition = %.3f'%(np.sum(preds == val_half_Y) * 1.0/preds.shape[0]))
#acc = 0
#for i in range(preds.shape[0]):
#    if (preds[i] == val_half_Y[i])

(445,)
accuracy on valition = 0.796


In [103]:
lr_1 = linear_model.LogisticRegression()
train_half_X_1 = features
train_half_Y_1 = labels
lr_1.fit(train_half_X, train_half_Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [104]:
#print 'model: logit(p(yc=1|x)) = %f + %f * BMI' % (lr_1.intercept_, lr_1.coef_)
print(lr_1.intercept_)
print(lr_1.coef_)

[1.73134639]
[[ 1.49826151e+00  7.21679025e-01 -4.88594137e-01 -2.34808989e+00
  -4.53401632e-02 -4.22526863e-01  5.78412507e-02  1.38810597e-03
   2.27571300e-01  9.77941197e-01  5.25833898e-01]]


In [105]:
with open('train_titanic.csv', 'r') as fr:
    freader = csv.reader(fr)
    cnt = 0
    for eachLine in freader:
        cnt += 1
        if (cnt > 1):
            print(type(eachLine[9]))
            break

<type 'str'>


In [115]:
with open('test_titanic.csv', 'r') as fr:
    freader = csv.reader(fr)
    cnt = 0
    labels = []
    features = []
    for eachLine in freader:
        cnt += 1
        if (cnt > 1):
            feature = np.zeros(shape=(11, ))
            feature[int(eachLine[1])-1] = 1
            feature[3] = int(eachLine[3] == 'male')
            try:
                feature[4] = float(eachLine[4])
            except:
                feature[4] = 30
            feature[5] = int(eachLine[5])
            feature[6] = int(eachLine[6])
            try:
                feature[7] = float(eachLine[8])
            except:
                feature[7] = 7.25
            offset = 0
            if (eachLine[10] == 'S'):
                offset = 0
            elif (eachLine[10] == 'C'):
                offset = 1
            else:
                offset = 2
            feature[8+offset] = 1
            features.append(feature)
            labels.append(int(eachLine[1]))

    features = np.array(features, dtype = float)
    print(features.shape)
            
        

(418, 11)


In [116]:
preds = lr_1.predict(features)
print(preds.shape)


(418,)
accuracy on valition = 0.000


/Users/wangjialei/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:5: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """


In [117]:
print(preds)

[0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 1 0 1
 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 1 1 0 1 1
 1 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1
 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0
 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 1 0 1 1 0
 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0
 0 1 1 1 1 1 0 1 0 0 0]


In [127]:
with open('eggs.csv', 'w') as csvfile:
    Iwriter = csv.writer(csvfile)
    Iwriter.writerow(['PassengerId'] + ['Survived'])
    index = 892
    for k in preds:                                   
        Iwriter.writerow([index, k])
        index = index + 1